name = "TensorQCS"
uuid = "da12aa28-41b5-415a-b72f-86f814ffef72"
authors = ["nzy1997"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
